scenario:
  base_scenario: "Core"
  forecast_scenarios: ["High", "Low", "Behabioural"]
  forecast_year: 2046

paths:
  step2_outputs:
    planning_households_difference_file: "Outputs/2_Extended_NTEM_Targets/High_planning_HHs_difference.csv"
    planning_jobs_difference_file: "Outputs/2_Extended_NTEM_Targets/High_planning_jobs_difference.csv"
    planning_under16_difference_file: "Outputs/2_Extended_NTEM_Targets/High_planning_under16_difference.csv"

  step3_inputs:
    avzn_file: "Step3/Inputs/avzn31ft.txt"

  step4_inputs:
    cozn_file: "cozn31ft.txt"
    core_car_ownership_file: "Core_co.csv"
    high_car_ownership_file: "High_co.csv"