general:
  run_step2: True
  run_step3: False
  run_step4: False


step2_config:
  input_directory: "C://Users//hmackenzie//OneDrive - SystraGroup//LEIM_Python//New_Tool//Inputs//Step2"
  output_directory: "C://Users//hmackenzie//OneDrive - SystraGroup//LEIM_Python//New_Tool//Outputs//Step2"
  years: ['2019', '2026', '2031', '2036', '2046'] 
  scenarios: ['Core', 'Low', 'Behavioural','High'] 


step3_config:
  input_directory: "C://Users//hmackenzie//OneDrive - SystraGroup//LEIM_Python//New_Tool//Inputs//Step3"
  output_directory: "C://Users//hmackenzie//OneDrive - SystraGroup//LEIM_Python//New_Tool//Outputs//Step3"


step4_config:
  input_directory: "C://Users//hmackenzie//OneDrive - SystraGroup//LEIM_Python//New_Tool//Inputs//Step4"
  output_directory: "C://Users//hmackenzie//OneDrive - SystraGroup//LEIM_Python//New_Tool//Outputs//Step4"